Use Airflow variable for Google Drive API key in analytics DAG
Metro-Records/la-metro-dashboard pull request #125
Opened 2024-01-05 15:54 UTC by antidipyramid

## Overview

This PR transitions to using an Airflow variable (set in the Airflow web GUI) to store the Google Service Account API Key used in the analytics DAG. 

### Checklist

Handles #123 

- [x] PR has a descriptive enough title to be useful in changelogs

## Testing Instructions

 * Create an Airflow variable (located in `Admin > Variables` in the toolbar) called `google_service_acct_api_key` (the key is in Bitwarden under `LA Metro Google Service Account Key`)
 * Run the analytics DAG

2024-01-05 20:13 UTC, fgregg requested changes
this is a surprising way to access a variable. I understand that it's possible because of jinja templating, but that's not a normal way that i think about these files as templates.

could you access it the other way the docs suggest:

from airflow.models import Variable

```
"GOOGLE_SERVICE_ACCT_API_KEY": Variable.get("google_service_account_key")
```

2024-01-05 20:23 UTC, antidipyramid commented
@fgregg I agree it's odd! But on the [Best Practices](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#airflow-variables) page, Airflow recommends against calling `Variable` from top-level DAG code.

> Using Airflow Variables yields network calls and database access, so their usage in top-level Python code for DAGs should be avoided as much as possible...

> In top-level code, variables using jinja templates do not produce a request until a task is running, whereas, Variable.get() produces a request every time the dag file is parsed by the scheduler if caching is not enabled.

My understanding is that that means we should use the Jinja template syntax.

2024-01-05 20:32 UTC, fgregg commented
okay, then let's add a section in the README explaining the use of this pattern.

2024-01-05 20:34 UTC, fgregg commented
Actually, no. let's do it the not-recommended way for now. the network call is to it's own self, and the overhead of that call worth avoiding this surprising pattern.

2024-01-16 15:50 UTC, antidipyramid commented
@fgregg Any more comments on this one?

2024-01-16 16:03 UTC, fgregg approved these changes

2024-01-16 19:51 UTC, merged